packages:
  - packages/*
  - examples/*
  - docs

allowBuilds:
  better-sqlite3: true
  esbuild: true

catalog:
  typescript: ~5.9.3
  vitest: ^4.1.11
  tsdown: ^0.23.0
  "@types/node": ^22.20.2
  "@types/express": ^5.0.6
  express: ^5.2.1
  cookie: ^2.0.1
  dotenv: ^17.4.1
  keyv: ^5.6.0
  "@keyv/redis": ^5.1.6
  jose: ^6.2.12
  "@scalar/express-api-reference": ^0.10.18
  drizzle-orm: ^0.45.2
  drizzle-kit: ^0.31.10
  better-sqlite3: ^13.0.3
  "@types/better-sqlite3": ^9.6.0
  ioredis: ^5.11.1
  ioredis-mock: ^8.13.1
  "@types/ioredis-mock": ^8
  "@node-rs/argon2": ^2.2.1
  busboy: ^1.6.0
  "@types/busboy": ^1.5.4
  file-type: ^22.1.0
  pino: ^10.3.1
  pino-pretty: ^13.1.3
  zod: ^4.6.2
  valibot: ^1.5.0
  "@valibot/to-json-schema": ^1.8.0
  arktype: ^2.2.3
  tsx: ^4.23.13

minimumReleaseAgeExclude:
  - zod@4.6.2
  - '@valibot/to-json-schema@1.8.0'
